### ISSUE TITLE
Plugin not working in Sketch 50.2

### ISSUE THREAD

**Issue by ghost** [sureskumar/single-border#5]
Plugin not working in Sketch 50.2

**Comment by zcallan** [comment]
It's working for me in 50.2 if I use the dropdown menu to use the plugin. (`Plugins` -> `Single Border` -> `Single Border`).

I have another plugin that clashes with the `CMD+SHIFT+B` shortcut so I can't comment on whether the shortcut has started clashing with a new feature from 50.2.

**Comment by ghost** [comment]
This still doesn't work. The shortcut keys work fine. The issue is the border is not created on the edge on the selected rectangle

**Comment by sureskumar** [comment]
Hey Tommy, I am not able to replicate the error at my end :( can you provide screenshots, OS version, etc
