### ISSUE TITLE
Plugin not working in Sketch 47.1

### ISSUE THREAD

**Issue by anandvip** [sureskumar/single-border#6]
Single Border Plugin not working in 47.1

**Comment by sureskumar** [comment]
Hey Vipul, I had to update bunch of stuff in this plugin to make it work in Sketch 50.2. If you are using an earlier sketch version, please download the plugin from here https://github.com/sureskumar/single-border/archive/09ec9046ba714b61d24caec3cb631af613f47fd2.zip
