### ISSUE TITLE
Not working with Sketch v46.2

### ISSUE THREAD

**Issue by phil9690** [sureskumar/single-border#8]
Hi, I have the plugin installed, but when I try to add a single border it never adds the border. I'm using Sketch Version 46.2.

**Comment by sureskumar** [comment]
Hi, please update the sketch app to ver 52 and try again. Cheers!

**Comment by phil9690** [comment]
@sureskumar thanks for the update.

You should probably change this line in the docs to specify the minimum version it will work with to avoid this question again in the future.
https://github.com/sureskumar/single-border/blame/master/README.md#L31
